version: "3.2"
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'dev'
      MYSQL_DATABASE: 'dev'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - lara101        
      
  lara101:
    build:
      context: .
      dockerfile: Dockerfile
    image: omar2023/lara101  
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 8080:80  
    networks:
      - lara101

networks:
  lara101:
    driver: bridge
volumes:
  my-db:
   