name: laramicro app CI yaml Build

on: 
  push:
    branches: 
      - master

jobs:
  build-docker-image-push-it-to-docker-hub:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: dockerhub-login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: build and push image to dockerhub
        env:
          REPO: ${{ secrets.DOCKER_HUB_REPO }}
          TAG:  laramicro-v-${{ github.sha }}
        run: |
         docker-compose up -d 
         docker push $REPO:$TAG  
         docker logout  

       

